export { PageError } from "./page-error"
export { PageLogin } from "./page-login"
export { PageRecover } from "./page-recover"
export { PageRegistration } from "./page-registration"
export { PageResetPassword } from "./page-reset-password"
